# Generated by Django 6.0 on 2026-06-13 19:25

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('projects', 'Projects'), ('training', 'Training'), ('contact', 'Contact')], max_length=64, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('eyebrow', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('stats', models.JSONField(blank=True, default=content.models.list_default)),
                ('filters', models.JSONField(blank=True, default=content.models.list_default)),
                ('application_steps', models.JSONField(blank=True, default=content.models.list_default)),
                ('contact', models.JSONField(blank=True, default=content.models.dict_default)),
                ('inquiry_types', models.JSONField(blank=True, default=content.models.list_default)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'page content',
                'verbose_name_plural': 'page content',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('long_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Planning', 'Planning'), ('On Hold', 'On Hold')], default='Active', max_length=32)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(blank=True, default=content.models.list_default)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('image_key', models.CharField(blank=True, max_length=255)),
                ('gallery', models.JSONField(blank=True, default=content.models.list_default)),
                ('team', models.JSONField(blank=True, default=content.models.list_default)),
                ('collaborators', models.JSONField(blank=True, default=content.models.list_default)),
                ('funding', models.CharField(blank=True, max_length=255)),
                ('impact', models.JSONField(blank=True, default=content.models.list_default)),
                ('route', models.CharField(blank=True, max_length=255)),
                ('github_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('publication_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('level', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='training-programs/')),
                ('image_key', models.CharField(blank=True, max_length=255)),
                ('icon_name', models.CharField(blank=True, max_length=255)),
                ('route', models.CharField(blank=True, max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('curriculum', models.JSONField(blank=True, default=content.models.list_default)),
                ('prerequisites', models.TextField(blank=True)),
                ('outcomes', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=255)),
                ('format', models.CharField(blank=True, max_length=255)),
                ('certification', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
