# Generated by Django 6.0 on 2026-06-13 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='projects/uploads/')),
                ('upload_type', models.CharField(choices=[('image', 'Image'), ('flyer', 'Flyer'), ('document', 'Document'), ('other', 'Other')], default='image', max_length=32)),
                ('is_public', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='content.project')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgramUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='training-programs/uploads/')),
                ('upload_type', models.CharField(choices=[('image', 'Image'), ('flyer', 'Flyer'), ('document', 'Document'), ('other', 'Other')], default='flyer', max_length=32)),
                ('is_public', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='content.trainingprogram')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
