# Generated by Django 6.0 on 2026-06-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_projectupload_trainingprogramupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='projectupload',
            name='file',
            field=models.FileField(max_length=500, upload_to='projects/uploads/'),
        ),
        migrations.AlterField(
            model_name='trainingprogram',
            name='image',
            field=models.ImageField(blank=True, max_length=500, upload_to='training-programs/'),
        ),
        migrations.AlterField(
            model_name='trainingprogramupload',
            name='file',
            field=models.FileField(max_length=500, upload_to='training-programs/uploads/'),
        ),
    ]
