# Generated by Django 6.0 on 2026-06-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional external image URL, for example a Cloudinary delivery URL.', max_length=1000, verbose_name='image URL'),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional external image URL, for example a Cloudinary delivery URL.', max_length=1000, verbose_name='image URL'),
        ),
    ]
